const list = [
  {
    id: 'n2',
    tenhocbong:
      'Học Bổng Bán Phần Bậc Cử Nhân Và Thạc Sĩ Của Chính Phủ Hà Lan 2020',
    nguon: 'Công ty VNG',
    giatri: 'Giá trị: €5,000',
    loai: 'Loại: Bán phần',
    quocgia: 'Nước: Hà Lan',
    doituong: 'Đối tượng: Học sinh, sinh viên',
    slot: 20,
    view: 100,
    nganh: 'Ngành: Bất kỳ',
    avatar: require('../assets/vng.png'),
    cover: require('../assets/scholar1.jpg'),
  },
  {
    id: 'n1',
    tenhocbong: 'Học Bổng MBA Tại Trường Đại Học Canada West (UCW)',
    nguon: 'Công ty FPT',
    giatri: 'Giá trị: 9.720 CAD',
    loai: 'Loại: Toàn phần',
    quocgia: 'Nước: Canada',
    doituong: 'Đối tượng: Học sinh, sinh viên',
    slot: 20,
    view: 100,
    nganh: 'Ngành: Bất kì',
    avatar: require('../assets/fpt.png'),
  },
  {
    id: 'n3',
    tenhocbong:
      'Học Bổng Toàn Phần MEXT E3 Program Bậc Thạc Sĩ Và Tiến Sĩ Đa Ngành Tại Đại Học Hokkaido 2020 ',
    nguon: 'Công ty FPT',
    giatri: 'Giá trị: ¥45000',
    loai: 'Loại: Toàn phần',
    quocgia: 'Nước: Nhật Bản',
    doituong: 'Đối tượng: Sinh viên đã tốt nghiệp',
    slot: 20,
    view: 100,
    nganh: 'Ngành: 13 ngành',
    avatar: require('../assets/fpt.png'),
  },
  {
    id: 'n4',
    tenhocbong:
      'Chương Trình Học Bổng Toàn Phần Bậc Thạc Sĩ Của Fulbright Vietnamese Student Program 2021-2022',
    nguon: 'Công ty VNG',
    giatri: 'Giá trị: 10000USD',
    loai: 'Loại: Toàn phần',
    quocgia: 'Nước: Mỹ',
    doituong: 'Đối tượng: Sinh viên đã tốt nghiệp ',
    slot: 20,
    view: 100,
    nganh: 'Ngành: 20 ngành',
    avatar: require('../assets/vng.png'),
    cover: require('../assets/scholar.jpg'),
  },
];
export {list};
